---
- name: Load distribution variables
  ansible.builtin.include_vars:
    file: "{{ 'arch.yaml' if ansible_facts['os_family'] == 'Archlinux' or ansible_facts['distribution'] == 'Archlinux' else 'fedora.yaml' }}"

- name: Install base packages
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present

- name: Set login shell
  ansible.builtin.user:
    name: "{{ dotfiles_user }}"
    shell: "{{ base_login_shell }}"
