# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist USE flag enabled
VIDEO_CARD="intel"
MAKEOPTS="-j4 -l5"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
EMERGE_DEFAULT_OPTS="--ask --quiet-build --keep-going=y --with-bdeps=y"
ACCEPT_LICENSE="*"

USE="${USE} networkmanager"
FEATURES="${FEATURES} getbinpkg binpkg-request-signature"
# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
