---
virtualization_packages:
  - qemu-kvm
  - libvirt
  - libvirt-daemon-kvm
  - libvirt-daemon-config-network
  - libvirt-nss
  - virt-manager
  - virt-viewer
  - virt-install
  - guestfs-tools
  - edk2-ovmf
  - swtpm
  - virtiofsd
  - chezdav
  - libphodav
  - python3-libvirt

virtualization_pool_dir: VMs
