---
- name: Load distribution variables
  ansible.builtin.include_vars:
    file: "{{ 'arch.yaml' if ansible_facts['os_family'] == 'Archlinux' or ansible_facts['distribution'] == 'Archlinux' else 'fedora.yaml' }}"

- name: Install development packages
  ansible.builtin.package:
    name: "{{ development_packages }}"
    state: present

- name: Install development tools with Go
  ansible.builtin.command:
    cmd: "go install {{ item }}"
  become: false
  environment:
    GOBIN: "{{ dotfiles_home }}/.local/bin"
    PATH: "{{ dotfiles_home }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  loop: "{{ development_go }}"
  when: development_go is defined and development_go | length > 0
  changed_when: false

- name: Install development tools with pipx
  community.general.pipx:
    name: "{{ item }}"
    state: install
  become: false
  environment:
    PIPX_HOME: "{{ dotfiles_home }}/.local/pipx"
    PIPX_BIN_DIR: "{{ dotfiles_home }}/.local/bin"
  loop: "{{ development_pipx }}"
