hostname="bsd"
wlans_iwlwifi0="wlan0"
ifconfig_wlan0="WPA DHCP"
ifconfig_wlan0_ipv6="inet6 accept_rtadv"
create_args_wlan0="country US regdomain FCC"
sshd_enable="YES"
ntpd_enable="YES"
powerd_enable="YES"
moused_nondefault_enable="NO"
dumpdev="AUTO"
zfs_enable="YES"
seatd_enable="YES"
dbus_enable="YES"
kld_list="i915kms cuse"
autofs_enable="YES"
webcamd_enable="YES"
linux_enable="YES"
jail_enable="YES"
hcsecd_enable="YES"
