---
gnome_packages:
  - gnome
  - gnome-tweaks
  - gpaste
  - gnome-shell-extension-appindicator
  - seahorse
  - gvfs-mtp
  - android-file-transfer
  - errands
  - newsflash
  - amberol
  - switcheroo
  - fretboard
  - solanum
  - papers
