---
dev_packages:
  - python
  - pre-commit
  - uv
  - go
  - nodejs
  - npm
  - github-cli
  - jujutsu
  - imagemagick
  - emacs
  - gdb
  - rust

  # DevOps
  - ansible
  - helm
  - opentofu
  - kubectl
  - k9s

dev_npm:
  - "@anthropic-ai/claude-code"
  - "@agentclientprotocol/claude-agent-acp"

dev_go: []

dev_docker_packages:
  - podman
  - podman-compose
  - podman-docker

dev_virt_packages:
  - qemu-desktop
  - virtiofsd
  - libvirt
  - virt-viewer
  - edk2-ovmf
