---
dotfiles_repo: "{{ playbook_dir | dirname }}"

distro: "{{ {'Archlinux': 'arch', 'Gentoo': 'gentoo', 'Debian': 'debian'}[ansible_facts['distribution']] }}"

flatpak_package: flatpak

dotfiles_stow_ignore:
  - sway
  - waybar
  - fuzzel
  - mako

dotfiles_stow_ignore_re: "^({{ dotfiles_stow_ignore | join('|') }})$"
