---
dotfiles_repo: "{{ playbook_dir | dirname }}"

dotfiles_stow_ignore:
  - sway
  - waybar
  - fuzzel
  - mako
  - assets

dotfiles_stow_ignore_re: "^({{ dotfiles_stow_ignore | join('|') }})$"

nas_shares:
  - { share: video, path: /mnt/nas/media }
  - { share: home, path: /mnt/nas/backup }
