---
- name: Load distribution variables
  ansible.builtin.include_vars:
    file: "{{ distro }}.yaml"

- name: Add application apt repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
  loop: "{{ apps_apt_repos }}"
  loop_control:
    label: "{{ item.name }}"
  register: apps_apt_repos_result
  when: distro == 'debian'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - distro == 'debian'
    - apps_apt_repos_result is changed

- name: Install applications
  ansible.builtin.package:
    name: "{{ apps_packages }}"
    state: present

- name: Enable application services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ apps_services }}"
  when: ansible_facts['service_mgr'] == 'systemd'

- name: Install application flatpaks
  community.general.flatpak:
    name: "{{ apps_flatpaks }}"
    state: present
    method: system
    remote: flathub
