---
media_packages:
  - mpv
  - imv
  - ytfzf
  - aria2 

  # Reading
  - foliate
  - zathura
  - zathura-pdf-mupdf
  - zathura-cb

  # NAS
  - cifs-utils

media_flatpaks:
  - io.github.screwys.Rufin
