---
- name: Load distribution variables
  ansible.builtin.include_vars:
    file: "{{ distro }}.yaml"

- name: Add development apt repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
  loop: "{{ dev_apt_repos }}"
  loop_control:
    label: "{{ item.name }}"
  register: dev_apt_repos_result
  when: distro == 'debian'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - distro == 'debian'
    - dev_apt_repos_result is changed

- name: Install development packages
  ansible.builtin.package:
    name: "{{ dev_packages }}"
    state: present

- name: Install development tools with pipx
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source | default(omit) }}"
    state: latest
  become: false
  loop: "{{ dev_pipx }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install development tools with Go
  ansible.builtin.command:
    cmd: "go install {{ item }}"
  become: false
  environment:
    GOBIN: "{{ dotfiles_home }}/.local/bin"
    PATH: "{{ dotfiles_home }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  loop: "{{ dev_go }}"
  changed_when: false

- name: Install virtualization packages
  ansible.builtin.package:
    name: "{{ dev_virt_packages }}"
    state: present

- name: Enable libvirtd
  ansible.builtin.systemd_service:
    name: libvirtd.service
    enabled: true
    state: started
  when: ansible_facts['service_mgr'] == 'systemd' and dev_virt_packages | length > 0

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ dotfiles_user }}"
    groups: libvirt
    append: true
  when: dev_virt_packages | length > 0

- name: Install Docker packages
  ansible.builtin.package:
    name: "{{ dev_docker_packages }}"
    state: present

- name: Enable Podman socket
  ansible.builtin.systemd_service:
    name: podman.socket
    enabled: true
    state: started
  when: ansible_facts['service_mgr'] == 'systemd' and dev_docker_packages | length > 0
