---
development_packages:
  - python
  - python-pipx
  - pre-commit
  - uv
  - go
  - gopls
  - golangci-lint
  - nodejs
  - npm
  - github-cli
  - jujutsu
  - direnv
  - pandoc-cli
  - imagemagick
  - emacs
  - gdb
  - rust
  - rust-analyzer

development_pipx: []

development_go:
  - github.com/jorgerojas26/lazysql@latest
