---
development_packages:
  - python3
  - pipx
  - pre-commit
  - uv
  - golang
  - gopls
  - golangci-lint
  - nodejs24
  - nodejs24-npm
  - gh
  - jujutsu
  - direnv
  - pandoc-cli
  - ImageMagick
  - emacs
  - gdb
  - rust
  - cargo
  - rust-analyzer

development_pipx: []

development_go:
  - github.com/jorgerojas26/lazysql@latest
