---
sway_packages:
  - sway
  - swaybg
  - swaylock
  - swayidle
  - waybar
  - mako
  - fuzzel
  - grim
  - slurp
  - wl-clipboard
  - wmenu
  - cliphist
  - brightnessctl
  - nautilus
  - papirus-icon-theme

  # Applets
  - blueman
  - network-manager-applet
  - pavucontrol

  # Session
  - polkit-gnome
  - gnome-keyring
  - gcr

  # Portals
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal-gtk
