# Bind 'r' to reload tmux config
unbind R
bind-key R source-file ~/.tmux.conf \; display-message "Reloading tmux config…"

set -ga update-environment " WAYLAND_DISPLAY XDG_RUNTIME_DIR"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*256color:Tc"
set -ga terminal-overrides ",*:RGB"
set -sg escape-time 50
set -g base-index 1 # Start Windows and Panes from 1 instead of 0
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g history-limit 50000

# Options General
set-option -s focus-event on
set-option -s extended-keys on
set-option -g set-clipboard on

# Follow path on new window
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Keybinds
bind-key a send-prefix
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key r command-prompt -p "Rename session:" "rename-session '%%'"
bind-key S command-prompt -p "Session name:" "new-session -s '%%' \; switch-client -t '%%'"
bind-key b run-shell "tmux list-sessions | cut -d: -f1 | awk 'BEGIN {ORS=\" \"} {print \$0, NR, \"\\\"switch-client -t\", \$0 \"\\\"\"}' | xargs tmux display-menu -T 'Switch session'"

# Window switching with Alt
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# copy mode
setw -g mode-style 'fg=default bg=red bold'

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status on  
set -g status-format[1] ''
set -g status-position top
set -g status-justify centre
set -g status-style 'bg=default'
set -g status-left-length 100
set -g status-right ''
set -g status-left-style 'fg=#bd93f9 bg=default'
set -g status-left "   [#S] "

setw -g window-status-current-style 'fg=orange bg=default bold'
setw -g window-status-current-format '#I: #W '
setw -g window-status-style 'fg=grey bg=default'
setw -g window-status-format ' #I #W #[fg=yellow]'
setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
set -g message-style 'fg=yellow bg=default bold'

# plugins
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux
