[colors-dark]
alpha=1
background=121110
bright0=917e6b
bright1=f75341
bright2=98bc37
bright3=fed06e
bright4=68a8e4
bright5=ff5c8f
bright6=2be4d0
bright7=fce8c3
flash=7f7f00
flash-alpha=0.500000
foreground=fce8c3
regular0=121110
regular1=ef2f27
regular2=519f50
regular3=fbb829
regular4=2c78bf
regular5=e02c6d
regular6=0aaeb3
regular7=c5b088
cursor=121110 fed06e

[colors-light]
foreground=1C1B19
background=FBF1DC
regular0=1C1B19
regular1=C01B12
regular2=3D6B12
regular3=8A5300
regular4=1E5F9E
regular5=A81050
regular6=06666B
regular7=F3E4C0
bright0=7A6A50
bright1=E2493B
bright2=5A8A24
bright3=A85200
bright4=3C7FBE
bright5=C62F74
bright6=0F8489
bright7=FBF1DC
cursor=1C1B19 FBF1DC

[csd]
#border-width=0
#preferred=none
#size=0

[cursor]
blink=yes
style=beam

[main]
dpi-aware=no
font=Fira Code:size=13
pad=0x10
term=xterm-256color

[mouse]
hide-when-typing=yes

[scrollback]
lines=15000

[key-bindings]
color-theme-toggle=Super+Shift+t
