[colors-dark]
alpha=0.95
background=121110
bright0=917e6b
bright1=f75341
bright2=98bc37
bright3=fed06e
bright4=68a8e4
bright5=ff5c8f
bright6=2be4d0
bright7=fce8c3
flash=7f7f00
flash-alpha=0.500000
foreground=fce8c3
regular0=121110
regular1=ef2f27
regular2=519f50
regular3=fbb829
regular4=2c78bf
regular5=e02c6d
regular6=0aaeb3
regular7=c5b088
cursor=121110 fed06e

[colors-light]
alpha=0.95
foreground=3c3836
background=fbf1c7
regular0=282828
regular1=9d0006
regular2=79740e
regular3=b57614
regular4=076678
regular5=8f3f71
regular6=427b58
regular7=3c3836
bright0=928374
bright1=cc241d
bright2=98971a
bright3=d79921
bright4=458588
bright5=b16286
bright6=689d69
bright7=ebdbb2
cursor=3c3836 fbf1c7

[csd]
#border-width=0
#preferred=none
#size=0

[cursor]
blink=yes
style=beam

[main]
dpi-aware=no
font=Fira Code:size=13
pad=10x0
term=xterm-256color

[mouse]
hide-when-typing=yes

[scrollback]
lines=15000

[key-bindings]
color-theme-toggle=Super+Shift+t
