---
development_packages:
  - python3
  - python3-pip
  - pipx
  - uv
  - golang
  - gopls
  - nodejs24
  - nodejs24-npm
  - gh
  - direnv
  - pandoc-cli
  - ImageMagick
  - emacs
  - gdb
  - clang
  - clang-tools-extra
  - rust
  - cargo
  - rust-analyzer
  - zed
  - dbeaver-bin

development_pipx:
  - pyright
