---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

virtualization_packages:
  - vagrant
  - vagrant-libvirt
  - qemu-kvm
  - libvirt
  - libvirt-daemon-kvm
  - libvirt-daemon-config-network
  - libvirt-nss
  - virt-manager
  - virt-viewer
  - virt-install
  - guestfs-tools
  - edk2-ovmf
  - virtiofsd
  - chezdav
  - libphodav
