---
security_packages:
  - wireshark
  - debsecan

  # Pentest
  - nmap
  - gobuster
  - smbclient
  - proxychains4
  - rlwrap
  - sshuttle
  - freerdp3-wayland
  - remmina
  - checksec
  - binwalk

  # Exploit dev
  - python3-pwntools
  - python3-ropgadget

security_flatpaks:
  - net.portswigger.BurpSuite-Community
  - re.rizin.cutter
  - re.rizin.cutter.plugin.rz-ghidra

security_go:
  - github.com/ffuf/ffuf/v2@latest
  - github.com/projectdiscovery/dnsx/cmd/dnsx@latest
  - github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
  - github.com/nicocha30/ligolo-ng/cmd/proxy@latest
  - github.com/nicocha30/ligolo-ng/cmd/agent@latest

security_go_links:
  ligolo-proxy: proxy
  ligolo-agent: agent

security_pipx:
  - name: pwndbg
    source: git+https://github.com/pwndbg/pwndbg

seclists_dir: /usr/share/seclists
