---
- hosts: localhost
  become: true  # Run tasks with sudo
  gather_facts: true  # Required to detect OS

  tasks:
    - name: Enable Ghostty
      community.general.copr:
        state: enabled
        name: pgdev/ghostty
      when: ansible_distribution == "Fedora"

    - name: Enable LazyGit
      community.general.copr:
        state: enabled
        name: atim/lazygit
      when: ansible_distribution == "Fedora"

    - name: Install packages on Fedora
      dnf:
        name:
          - curl
          - git
          - cmake
          - python3
          - python3-pip
          - i3
          - i3lock
          - rofi
          - feh
          - alacritty
          - polybar
          - zsh
          - neovim
          - nodejs
          - dunst
          - adwaita-icon-theme
          - npm
          - pamixer
          - tmux
          - ranger
          - golang
          - rust
          - cargo
          - rust-analyzer
          - texlive-collection-fontsrecommended
          - texlive-capt-of
          - texlive-ulem
          - texlive-wrapfig
          - pdflatex
          - libtool
          - mpv
          - emacs
        state: present
      when: ansible_distribution == "Fedora"

    - name: Install hyprland Fedora
      dnf:
        name:
          - hyprland 
          - hyprpaper 
          - hyprlock 
          - hypridle 
          - wofi 
          - waybar
        state: present
      when: ansible_distribution == "Fedora"

    - name: Install flatpak packages
      community.general.flatpak:
        name:
          - org.gnome.Extensions
          - org.getzola.zola
          - com.viber.Viber
          - com.jeffser.Alpaca
          - dev.restfox.Restfox
          - com.github.johnfactotum.Foliate
          - ca.desrt.dconf-editor
          - com.github.IsmaelMartinez.teams_for_linux
          - com.github.neithern.g4music
      when: ansible_distribution == "Fedora"

    - name: Install packages on Ubuntu
      apt:
        name:
          - curl
          - git
          - stow
          - cmake
          - python3
          - python3-pip
          - i3
          - i3lock
          - rofi
          - feh
          - alacritty
          - polybar
          - zsh
          - neovim
          - nodejs
          - dunst
          - adwaita-icon-theme
          - npm
          - pamixer
          - tmux
          - ranger
          - golang-go
          - rustc
          - cargo
          - rust-analyzer
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install packages on FreeBSD
      pkgng:
        name:
          - curl
          - git
          - stow
          - cmake
          - python3
          - i3
          - i3lock
          - rofi
          - feh
          - alacritty
          - polybar
          - zsh
          - neovim
          - node
          - dunst
          - adwaita-icon-theme
          - npm
          - pamixer
          - tmux
          - go
          - rust
          - rust-analyzer
        state: present
      when: ansible_distribution == "FreeBSD"

    - name: Setup ZSH
      become: false
      shell: |
        chsh -s '$(command -v zsh)'
        sh -c '$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)'
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestion
         
    - name: Download and install Nerd Fonts
      become: false
      shell: |
        mkdir -p ~/.local/share/fonts
        cp -R ../fonts/Hack/* ~/.local/share/fonts/
        fc-cache -fv

    - name: Auto-install Lazy.nvim plugins
      become: false
      shell: |
        nvim --headless +Lazy! +qall
      args:
        executable: /bin/sh
      environment:
        XDG_CONFIG_HOME: ~/.config
        XDG_DATA_HOME: ~/.local/share


