---
- hosts: localhost
  become: true  # Run tasks with sudo
  gather_facts: true  # Required to detect OS

  tasks:
    - name: Install packages on Ubuntu
      apt:
        name:
          - curl
          - git
          - stow
          - cmake
          - python3
          - python3-pip
          - i3
          - i3lock
          - rofi
          - feh
          - alacritty
          - polybar
          - zsh
          - neovim
          - nodejs
          - dunst
          - adwaita-icon-theme
          - npm
          - pamixer
          - tmux
          - ranger
          - golang-go
          - rustc
          - cargo
          - rust-analyzer
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Enable Ghostty
      community.general.copr:
        state: enabled
        name: pgdev/ghostty
      when: ansible_distribution == "Fedora"

    - name: Enable LazyGit
      community.general.copr:
        state: enabled
        name: atim/lazygit
      when: ansible_distribution == "Fedora"

    - name: Install packages on Fedora
      dnf:
        name:
          - curl
          - git
          - cmake
          - python3
          - python3-pip
          - i3
          - i3lock
          - rofi
          - feh
          - alacritty
          - polybar
          - zsh
          - neovim
          - nodejs
          - dunst
          - adwaita-icon-theme
          - npm
          - pamixer
          - tmux
          - ranger
          - golang
          - rust
          - cargo
          - rust-analyzer
        state: present
      when: ansible_distribution == "Fedora"

    - name: Install flatpak packages
      community.general.flatpak:
        name:
          - org.gnome.Extensions
          - org.getzola.zola
          - com.viber.Viber
          - com.jeffser.Alpaca
          - dev.restfox.Restfox
          - com.github.johnfactotum.Foliate
          - ca.desrt.dconf-editor
          - com.github.IsmaelMartinez.teams_for_linux
          - com.github.neithern.g4music

    - name: Download and install Nerd Fonts
      become: false
      shell: |
        mkdir -p ~/.local/share/fonts
        cd ~/.local/share/fonts
        curl -fLo "Hack Regular Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
        fc-cache -fv
      args:
        creates: ~/.local/share/fonts/Hack\ Regular\ Nerd\ Font\ Complete.ttf

    - name: Auto-install Lazy.nvim plugins
      become: false
      shell: |
        nvim --headless +Lazy! +qall
      args:
        executable: /bin/bash
      environment:
        XDG_CONFIG_HOME: ~/.config
        XDG_DATA_HOME: ~/.local/share


