---
apps_packages:
  - firefox
  - mpv
  - gimp
  - zathura
  - zathura-pdf-mupdf
  - zathura-cb
  - zathura-ps
  - zathura-djvu
  - discord
  - fastfetch
  - foliate
  - halloy

apps_flatpaks:
  - com.bitwarden.desktop
  - md.obsidian.Obsidian
  - com.fastmail.Fastmail
  - io.github.screwys.Rufin
