---
apps_packages:
  - firefox
  - pinta
  - discord
  - fastfetch
  - pfetch-rs
  - halloy

apps_flatpaks:
  - com.bitwarden.desktop
  - md.obsidian.Obsidian
  - in.suyogtandel.picoforge
  - com.discordapp.Discord
