---
apps_packages:
  - firefox
  - pinta
  - zathura
  - zathura-pdf-mupdf
  - zathura-cb
  - discord
  - fastfetch
  - foliate
  - halloy
  - llama-cpp
  - ggml-blas

apps_flatpaks:
  - com.bitwarden.desktop
  - md.obsidian.Obsidian
  - com.fastmail.Fastmail
  - in.suyogtandel.picoforge
