---
apps_packages:
  - mpv
  - pinta
  - zathura
  - zathura-pdf-mupdf
  - zathura-cb
  - discord
  - fastfetch
  - foliate
  - halloy

apps_flatpaks:
  - com.bitwarden.desktop
  - md.obsidian.Obsidian
  - com.fastmail.Fastmail
  - io.github.screwys.Rufin
