---
apps_packages:
  - www-client/firefox-bin
  - app-misc/fastfetch

  # Overlay (GURU)
  - app-misc/pfetch
  - net-irc/halloy

apps_flatpaks:
  - com.bitwarden.desktop
  - md.obsidian.Obsidian
  - in.suyogtandel.picoforge
  - com.discordapp.Discord
