---
- name: Load distribution variables
  ansible.builtin.include_vars:
    file: "{{ 'arch.yaml' if ansible_facts['os_family'] == 'Archlinux' or ansible_facts['distribution'] == 'Archlinux' else 'fedora.yaml' }}"

- name: Install security packages
  ansible.builtin.package:
    name: "{{ security_packages }}"
    state: present

- name: Add user to wireshark group
  ansible.builtin.user:
    name: "{{ dotfiles_user }}"
    groups: wireshark
    append: true
