---
base_packages:
  # Boot & hardware
  - base
  - base-devel
  - linux
  - linux-firmware
  - mkinitcpio
  - efibootmgr
  - sudo
  - iwd
  - sof-firmware
  - intel-media-driver
  - libva-intel-driver
  - vulkan-intel
  - vulkan-nouveau
  - vulkan-radeon
  - xf86-video-amdgpu
  - xf86-video-ati
  - xf86-video-nouveau
  - zram-generator
  - fprintd
  - fwupd
  - smartmontools

  # Networking
  - networkmanager

  # Firewall
  - ufw

  # Snapshots
  - btrfs-progs
  - snapper

  # VCS
  - git

  # Core tools
  - ripgrep
  - fd
  - fzf
  - bat
  - eza
  - jq
  - tree
  - file
  - duf
  - htop
  - btop
  - yazi
  - rsync
  - stow
  - wl-clipboard
  - mtr
  - bind
  - whois
  - lsof
  - socat
  - wget
  - curl

  # Archiving
  - 7zip
  - unzip
  - zip
  - xz

  # Crypto
  - openssl
  - openssh
  - gnupg
  - pinentry
  - pass

  # Shell & editors
  - zsh
  - tmux
  - neovim
  - tree-sitter-cli
  - vim
  - nano
  - less

  # Terminal emulators
  - foot
  - ghostty

  # Package managers
  - nix

  # Fonts
  - noto-fonts
  - noto-fonts-emoji
  - ttf-dejavu
  - ttf-liberation
  - ttf-fira-code
  - ttf-jetbrains-mono
  - ttf-firacode-nerd

base_services:
  - NetworkManager.service
  - ufw.service

base_ucode:
  GenuineIntel: intel-ucode
  AuthenticAMD: amd-ucode

base_locale_file: /etc/locale.conf

base_login_shell: /usr/bin/zsh

base_nix: true
