---
base_packages:
  - git
  - cmake
  - gcc
  - make
  - ripgrep
  - fd
  - fzf
  - bat
  - eza
  - jq
  - tree
  - file
  - duf
  - htop
  - btop
  - rsync
  - rlwrap
  - stow
  - wl-clipboard
  - mtr
  - bind
  - whois
  - lsof
  - socat
  - wget
  - curl
  - 7zip
  - unzip
  - zip
  - xz
  - openssl
  - openssh
  - gnupg
  - pinentry
  - zsh
  - tmux
  - neovim
  - python-pynvim
  - vim
  - nano
  - less
  - foot
  - ghostty
  - nix

  # Fonts
  - noto-fonts
  - noto-fonts-emoji
  - ttf-dejavu
  - ttf-liberation
  - ttf-fira-code


base_login_shell: /usr/bin/zsh
