---
base_packages:
  - git
  - cmake
  - gcc
  - gcc-c++
  - make
  - ripgrep
  - fd-find
  - fzf
  - bat
  - eza
  - jq
  - tree
  - file
  - duf
  - htop
  - btop
  - rsync
  - stow
  - dnf-plugins-core
  - wl-clipboard
  - mtr
  - bind-utils
  - lsof
  - socat
  - wget2-wget
  - curl
  - 7zip
  - unzip
  - zip
  - xz
  - openssl
  - openssh-clients
  - gnupg2
  - pinentry-gnome3
  - zsh
  - tmux
  - neovim
  - python3-neovim
  - vim-enhanced
  - nano
  - less
  - foot
  - ghostty
  - nix

  # Fonts
  - google-noto-sans-fonts
  - google-noto-emoji-fonts
  - dejavu-sans-fonts
  - liberation-fonts
  - fira-code-fonts
  - jetbrains-mono-fonts
  - firacode-nerd-fonts

base_login_shell: /usr/bin/zsh
