---
- name: Install virtualization packages
  ansible.builtin.dnf5:
    name: "{{ virtualization_packages }}"
    state: present

- name: Enable libvirtd
  ansible.builtin.systemd_service:
    name: libvirtd.service
    enabled: true
    state: started

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ dotfiles_user }}"
    groups: libvirt
    append: true
