---
- name: Load distribution variables
  ansible.builtin.include_vars:
    file: "{{ 'arch.yaml' if ansible_facts['os_family'] == 'Archlinux' or ansible_facts['distribution'] == 'Archlinux' else 'fedora.yaml' }}"

- name: Install media packages
  ansible.builtin.package:
    name: "{{ media_packages }}"
    state: present

- name: Install media flatpaks
  community.general.flatpak:
    name: "{{ media_flatpaks }}"
    state: present
    method: system
    remote: flathub
