---
desktop_packages:
  - gdm
  - power-profiles-daemon
  - caligula

  # Bluetooth
  - bluez
  - bluez-utils
 
  # Networking
  - tailscale
  - networkmanager
  - openvpn
  - networkmanager-openvpn

  # Audio
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - wireplumber
  - gst-plugin-pipewire

desktop_services:
  - gdm.service
  - NetworkManager.service
  - power-profiles-daemon.service
  - tailscaled.service
