---
desktop_packages:
  - gnome
  - gnome-circle
  - gdm
  - power-profiles-daemon
  - networkmanager
  - bluez
  - bluez-utils

  # Audio
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - wireplumber
  - gst-plugin-pipewire

desktop_services:
  - gdm.service
  - NetworkManager.service
  - power-profiles-daemon.service
