---
desktop_supported_sessions:
  - sway
  - gnome

desktop_packages:
  - pipewire-jack

desktop_services: []

desktop_sway_packages:
  # Core
  - sway
  - swaybg
  - swaylock
  - swayidle
  - waybar
  - mako-notifier
  - fuzzel
  - grim
  - slurp
  - wmenu
  - cliphist
  - brightnessctl

  # Display manager
  - greetd

  # File manager & icons
  - nautilus
  - papirus-icon-theme

  # Applets
  - blueman
  - network-manager-applet
  - pavucontrol

  # Session
  - mate-polkit
  - gnome-keyring
  - gcr4

  # Portals
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal-gtk

  # Bluetooth & power
  - bluez
  - power-profiles-daemon

  # Audio
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - wireplumber
  - gstreamer1.0-pipewire

desktop_sway_services:
  - bluetooth.service
  - power-profiles-daemon.service

desktop_sway_user_units:
  - gcr-ssh-agent.socket

desktop_sway_user_units_disabled: []

desktop_greetd_user: _greetd

desktop_gnome_packages:
  - gnome-core
  - gnome-tweaks
  - gpaste-2
  - gnome-shell-extension-gpaste
  - gnome-shell-extension-appindicator
  - seahorse
  - android-file-transfer
  - errands
  - amberol

desktop_gnome_flatpaks:
  - io.gitlab.news_flash.NewsFlash
  - io.gitlab.adhami3310.Converter
  - dev.bragefuglseth.Fretboard
  - org.gnome.Solanum

desktop_gnome_services:
  - gdm.service
  - bluetooth.service
