---
desktop_supported_sessions:
  - sway
  - gnome

desktop_packages:
  - pipewire-jack

desktop_services: []

desktop_sway_packages:
  # Core
  - sway
  - swaybg
  - swaylock
  - swayidle
  - waybar
  - mako-notifier
  - fuzzel
  - grim
  - slurp
  - wmenu
  - xwayland
  - wl-clipboard
  - cliphist
  - brightnessctl
  - playerctl

  # Display manager
  - greetd
  - tuigreet

  # File manager & icons
  - nautilus
  - papirus-icon-theme
  - udisks2
  - udiskie
  - gvfs
  - gvfs-backends

  # Applets
  - blueman
  - network-manager
  - network-manager-applet
  - nm-connection-editor
  - libnotify-bin
  - pavucontrol

  # Session
  - dbus-user-session
  - mate-polkit
  - gnome-keyring
  - libpam-gnome-keyring

  # GnuPG / smartcard
  - scdaemon
  - pinentry-gnome3

  # Portals
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal-gtk

  # Bluetooth & power
  - bluez
  - upower
  - power-profiles-daemon

  # Audio
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - wireplumber
  - gstreamer1.0-pipewire

desktop_greetd_user: _greetd

desktop_gnome_packages:
  - gnome-core
  - gnome-tweaks
  - gpaste-2
  - gnome-shell-extension-gpaste
  - gnome-shell-extension-appindicator
  - seahorse
  - android-file-transfer
  - errands
  - amberol

desktop_gnome_flatpaks:
  - io.gitlab.news_flash.NewsFlash
  - io.gitlab.adhami3310.Converter
  - dev.bragefuglseth.Fretboard
  - org.gnome.Solanum

desktop_gnome_services:
  - gdm.service
  - bluetooth.service
