---
desktop_supported_sessions:
  - sway

desktop_packages:
  - sys-power/tlp

desktop_services:
  - tlp.service
  - tlp-pd.service

desktop_sway_packages:
  # Core
  - gui-wm/sway
  - gui-apps/swaybg
  - gui-apps/swaylock
  - gui-apps/swayidle
  - gui-apps/waybar
  - gui-apps/mako
  - gui-apps/grim
  - gui-apps/slurp
  - gui-apps/wmenu
  - x11-base/xwayland
  - gui-apps/wl-clipboard
  - media-sound/playerctl

  # Display manager
  - gui-libs/greetd
  - gui-apps/tuigreet

  # File manager & icons
  - x11-misc/pcmanfm
  - gnome-base/gvfs
  - sys-fs/udisks
  - sys-fs/udiskie
  - x11-themes/papirus-icon-theme

  # Applets
  - net-misc/networkmanager
  - gnome-extra/nm-applet
  - media-sound/pavucontrol
  - net-wireless/blueman
  - x11-libs/libnotify

  # Session
  - gnome-base/gnome-keyring
  - mate-extra/mate-polkit

  # GnuPG / smartcard
  - app-crypt/gnupg
  - app-crypt/pinentry

  # Portals
  - sys-apps/xdg-desktop-portal-gtk
  - gui-libs/xdg-desktop-portal-wlr

  # Bluetooth & power
  - net-wireless/bluez
  - sys-power/upower

  # Audio
  - media-video/pipewire
  - media-video/wireplumber

  # Overlay (GURU)
  - gui-apps/fuzzel
  - app-misc/cliphist
  - app-misc/brightnessctl

desktop_sway_services:
  - bluetooth.service

desktop_sway_user_units:
  - pipewire.socket
  - pipewire-pulse.socket
  - wireplumber.service
  - gpg-agent.socket
  - gpg-agent-ssh.socket

desktop_greetd_user: greetd
